version: "3.8"
services:
  app:
    build: .
    restart: on-failure
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: ${DATABASE_URL_PRODUCTION}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}  # Fix typo here too
    volumes:
      - .:/app # Mount the local directory into the container
      - node_modules:/app/node_modules # Ensure node_modules inside the container is not overwritten
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:13-alpine
    restart: on-failure
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - postgres_database:/var/lib/postgresql/data/
    networks:
      - app-network

volumes:
  postgres_database:
  node_modules: 

networks:
  app-network:
