services:
  app:
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL_PRODUCTION}
      NODE_ENV: production
      AUTH_SECRET: ${AUTH_SECRET}
      AUTH_URL: ${AUTH_URL}
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_database:/var/lib/postgresql/data/
    networks:
      - app-network

volumes:
  postgres_database:

networks:
  app-network:
