version: "3.8"
services:
  backend:
    build: .
    restart: on-failure
    ports:
      - 4000:4000
    volumes:
      - .:/app
      - /app/node_modules
      - logs:/app/logs
    depends_on:
      - postgres

  postgres:
    image: postgres:13-alpine
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
  logs:
  redis_db_data:
    external: false